ABI Generation
ava-labs/hypersdk pull request #1301
Opened 2024-08-15 04:21 UTC by containerman17

Generate a JSON representation of all VM actions and their fields.

2024-08-15 13:40 UTC, richardpringle requested changes
Small spelling mistake

2024-08-15 13:40 UTC, richardpringle commented on chain/dependencies.go
> +	Marshal(p *codec.Packer)
```suggestion
type Marshaller interface {
	// Marshal encodes an [Action] as bytes.
	Marshal(p *codec.Packer)
```

2024-08-15 13:40 UTC, richardpringle commented on chain/transaction.go
> +		if marshaler, ok := action.(Marshaler); ok {
```suggestion
		if marshaller, ok := action.(Marshaller); ok {
```

2024-08-15 13:40 UTC, richardpringle commented on chain/transaction.go
> +			marshaler.Marshal(p)
```suggestion
		if marshaller, ok := action.(Marshaller); ok {
			marshaller.Marshal(p)
```

2024-08-21 14:35 UTC, containerman17 commented
Blocked by https://github.com/ava-labs/hypersdk/pull/1198

2024-08-27 07:02 UTC, containerman17 commented
Closed in favor of https://github.com/ava-labs/hypersdk/pull/1459

2024-08-28 09:34 UTC, closed without merging