Expose Program as Child of Runtime
ava-labs/hypersdk pull request #1533
Opened 2024-09-10 21:45 UTC by samliok

programs should be children of runtime as a runtime can hold multiple programs

2024-09-10 21:46 UTC, samliok commented on x/programs/runtime/util_test.go
> +		Runtime: t,
this hurt my rust brain @richardpringle

2024-09-11 15:27 UTC, richardpringle requested changes
Haha, don't worry about my comments about field names, just need to inline adding the program-id to the account-map.

2024-09-11 15:27 UTC, richardpringle commented on x/programs/runtime/util_test.go
> +		callContext: NewRuntime(
I know this might not be your code, but why is this called `callContext`?

2024-09-11 15:27 UTC, richardpringle commented on x/programs/runtime/util_test.go
> +			Mu:          test.NewTestDB(),
This is also a terrible name 😞, why not just call it `Db`?

2024-09-11 15:27 UTC, richardpringle commented on x/programs/runtime/util_test.go
> +}
This looks like a footgun for creating inconsistent state. This code is only used in the private context, right? Can we just inline it?

2024-09-11 15:27 UTC, richardpringle commented on x/programs/runtime/util_test.go
> +	t.AddProgramInstance(ProgramID(stringedID), account)
I think you can add this logic inside `AddProgram`. I know I said something about functions only doing one thing, but it makes sense to update the programs and accounts maps at the same time.

2024-09-11 15:40 UTC, richardpringle approved these changes

2024-09-11 15:40 UTC, merged