[WIP] Refactor Workload
ava-labs/hypersdk pull request #1668
Opened 2024-10-16 23:07 UTC by samliok

2024-10-17 16:15 UTC, richardpringle commented on examples/vmwithcontracts/go.mod
> +	github.com/BurntSushi/toml v1.3.2 // indirect
😮 @samliok, do you know who this is?

2024-10-17 17:18 UTC, samliok commented on examples/vmwithcontracts/go.mod
> +	github.com/BurntSushi/toml v1.3.2 // indirect
seems `go mod tidy` removed this

2024-10-17 21:11 UTC, samliok commented on examples/morpheusvm/tests/generator/mixed.go
> +	blsPriv, err := bls.GeneratePrivateKey()
i don't know how these bls keys were previously able to send balances. They are randomly generated and I can't seem to find where we allocate their balances.

2024-10-22 15:53 UTC, tsachiherman requested changes
Maybe I'm missing some file, but I can't find any use of `NewMultiAuthTxGenerator` or `multiAuthTxGenerator`.

2024-10-22 15:53 UTC, tsachiherman commented on examples/morpheusvm/cmd/morpheus-cli/cmd/chain.go
> +	RunE: func(_ *cobra.Command, _ []string) error {
that's 100% ok, but not really related to this PR.

2024-10-22 19:31 UTC, samliok commented on tests/workload/transactions.go
> +	submitClient := jsonrpc.NewJSONRPCClient(confirmUris[0])
should we load balance this selection?

2024-10-23 14:03 UTC, aaronbuchwald commented on tests/workload/transactions.go
> +	submitClient := jsonrpc.NewJSONRPCClient(confirmUris[0])
I don't think that's necessary

2024-10-23 15:05 UTC, aaronbuchwald submitted a review, later dismissed
LGTM - we can add back the functionality of `Workloads(...)` via https://github.com/ava-labs/hypersdk/pull/1667

2024-10-23 17:44 UTC, samliok commented on tests/workload/transactions.go
> +	for count := 0; count < blocks && height < targetheight; count++ {
I could extend this function to take in another argument `txPerBlock`, this is the same as the previous logic for generating blocks. Is it worth doing this is a follow up?

2024-10-23 17:49 UTC, aaronbuchwald commented on tests/workload/transactions.go
> +	for count := 0; count < blocks && height < targetheight; count++ {
This was actually a looser condition before, not more exact by requiring a specific number of transactions. We can produce blocks with no transactions in them and this function is intended to guarantee at least that number of blocks were produced, but only checks the height to allow empty blocks to be included.

Could we remove the extra check and leave this as only `height < targetHeight` ?

2024-10-23 17:56 UTC, aaronbuchwald approved these changes

2024-10-23 18:01 UTC, tsachiherman approved these changes

2024-10-23 18:26 UTC, merged