fee based txs/chunks selector
ava-labs/hypersdk pull request #1833
Opened 2024-12-13 18:29 UTC by tsachiherman

## What ?

This PR adds support for selecting the largest set of transactions / chunks based on their fees.

In this PR, I haven't included any usage of that algorithm, but rather just the algorithm itself ( + unit test )

## Description
LargestSet takes a slice of dimensions and a dimensions limit, and find the
largest set of dimensions that would fit within the provided limit. The return
slice is the list of indices relative to the provided [dimensions] slice.
note that the solution of the largest set is not
deterministic ( by the nature of the problem, there could be multiple "correct"
and different results )

### Algorithm ( high level )
1. Scaling: Each dimension is scaled relative to its respective limit
    to ensure fair comparison. This step normalizes the dimensions,
     preventing larger dimensions from dominating the selection process.
  2. Vector Sizing: Each dimension is treated as a vector, and its
     magnitude is calculated. This metric is used to assess the
     relative significance of each dimension.
  3. Greedy Selection: Dimensions are iteratively selected based on
     their scaled magnitudes, adding them to the subset until the size
     limit is reached. The greedy approach prioritizes the most significant
     dimensions, maximizing the overall subset size.

### Implementation notes:
 * Precision: To mitigate potential precision issues arising from
 small-scale dimensions, the function employs a scaling factor to
 amplify values before normalization. This ensures accurate calculations
 even when dealing with very small numbers.
 * Efficiency: The squared magnitude calculation is used as a proxy
 for Euclidean distance, optimizing performance without sacrificing
 accuracy for relative comparisons. This optimization avoids the
 computationally expensive square root operation.

## Motivation

The motivation behind this algorithm, in contrast to a FIFO ordering is the following -
1. When using a FIFO ordering ( more precisely, an optimistic attempt to include the transactions in the order they were received ), we are effectively using a random ordering. While this random ordering *could* be the ideal one, it would rarely be such.
2. Any stable algorithm ( such as this ) would allow us to prioritize transaction volume throughput over chunk/block saturation.

Consider the following ( single dimension ) challenge:
1. You have 5 transactions with the following weights [5,5,1,1,1]. The chunk capacity is 4.
2. Using FIFO, you would generate the following chunks [5][5][1,1,1]
3. Using the above algorithm, you would have generate the following [1,1,1][5][5].

This doesn't seems very meaningful as is, but imagine that you keep getting a stream of 3 transaction of weight 1 once every chunk/block ( high demand scenario ). Now, you would be generating the following:
1. In the case of FIFO: [5],[5],[1,1,1,1,1],[1,1,1,1,1]..
2. In case of the above algorithm: [1,1,1][1,1,1],...,[5],[5]

Hence, the network would favor TPS over chunk/block saturation. Big transaction would get pushed down the road.

2025-01-06 14:53 UTC, aaronbuchwald requested changes

2025-01-06 14:53 UTC, aaronbuchwald commented on fees/dimension.go
> +func (d Dimensions) AddDimentions(a Dimensions) (Dimensions, error) {
Can we fix the typo `AddDimensions` as well?

2025-01-06 15:22 UTC, tsachiherman commented on fees/set_test.go
> +			dimensions[i] = Dimensions{d % 1000, (d + 200) % 1000, (d + 400) % 1000, (d + 600) % 1000, (d + 800) % 1000}
It creates arbitrarily set of dimensions, that are uniformly distributes and are (mostly) non-identical.
I believe that for the purpose of evaluation the overall performance of the algorithm, it would provide a reasonable test-set. We could (naturally) pick a different test set, but I wouldn't expect any material performance difference.

2025-01-06 15:24 UTC, tsachiherman commented on fees/set.go
> +		}
you're correct that it would create a O(n^2) in the worst case scenario. I'll address that..

2025-01-06 15:47 UTC, tsachiherman commented on fees/set_test.go
> +}
The efficiency is linear... could you suggest what the worst case is ?

2025-01-06 17:08 UTC, aaronbuchwald commented on fees/set_test.go
> +}
Was suggesting this to catch the case before where it could be O(n^2) due to the append operation.

2025-01-09 21:59 UTC, aaronbuchwald approved these changes

2025-01-10 13:23 UTC, merged