[x/programs] add rust linter
ava-labs/hypersdk pull request #368
Opened 2023-08-18 12:32 UTC by hexfusion

This PR adds a github action and fixes for linting rust using clippy via the latest nightly.

2023-08-18 12:49 UTC, hexfusion commented on scripts/rust/tests.lint.sh
> +cargo +nightly fmt --all -- --config-path .rustfmt.nightly.toml --verbose --check || true
@samliok if we drop the `|| true` here these will run/error can you see if the output is reasonable if yes update the script? If not add a TODO to enable?

2023-08-18 14:57 UTC, patrick-ogrady commented on scripts/rust/tests.lint.sh
Is there a reason this isn't in `x/programs/rust`?

2023-08-20 22:45 UTC, samliok submitted a review, later dismissed

2023-08-20 22:45 UTC, samliok reviewed
looks good.

2023-08-21 00:53 UTC, patrick-ogrady approved these changes

2023-08-21 00:54 UTC, patrick-ogrady requested changes
Question on action

2023-08-21 00:54 UTC, patrick-ogrady commented on .github/workflows/rust-static-analysis.yml
> +permissions:
Why is this required?

2023-08-21 01:12 UTC, hexfusion commented on .github/workflows/rust-static-analysis.yml
> +permissions:
removed

2023-08-21 02:01 UTC, hexfusion commented on x/programs/rust/wasmlanche_sdk/src/host/mod.rs
> +/// Stores the bytes at value_ptr to the bytes at key ptr on the host.
I believe the proper syntax is the safety notice goes below the docs for the method/fucntion

/// Docs
///
/// # Safety

ref. https://doc.rust-lang.org/src/core/ptr/const_ptr.rs.html#406

2023-08-21 02:03 UTC, hexfusion commented on x/programs/rust/wasmlanche_sdk/src/host/mod.rs
> +/// Stores the bytes at value_ptr to the bytes at key ptr on the host.
```suggestion
/// Stores the bytes at value_ptr to the bytes at key ptr on the host.
///
/// # Safety
/// The caller must ensure that key_ptr + key_len and
/// value_ptr + value_len point to valid memory locations.
```

2023-08-21 15:02 UTC, patrick-ogrady approved these changes

2023-08-21 15:02 UTC, merged