[x/programs] Batch host function calls
ava-labs/hypersdk pull request #616
Opened 2023-11-10 22:46 UTC by samliok

The goal of this PR is to implement and benchmark the effects of batching host function calls. 

More details are described #593 

TODOs
 
- [ ] Create & Merge PR to allow dynamic sized function arguments
- [ ] Write `VerifyGuest` function in `rust` that verifies `n` ED signatures
   - [ ] Benchmark `VerifyGuest`
- [ ] Implement `Verify` host function in `go`
- [ ] Write `VerifyCallHost` function in `rust` that calls the `verify` host function for each ED signature
    - [ ] Benchmark `VerifyCallHost`
- [ ] Create an interface to allow WASM to batch host function calls
    - [ ]  Implement on rust side
    - [ ] implement on go side
- [ ] Write `VerifyBatch` function in `rust` that batches host function calls
    - [ ] Benchmark `VerifyBatch`

2023-11-14 17:19 UTC, richardpringle requested changes
As always, not all my comments are actual change requests... I'll go through and add an extra comment on the ones that I think are important.

2023-11-14 17:19 UTC, richardpringle commented on x/programs/rust/wasmlanche_sdk/Cargo.toml
> +ed25519-dalek = { version = "2.0.0", features = ["rand_core"]} # for the generate SigningKey function
🤔, should throw it behind a `crypto` feature flag for now. We can basically copy the types (depending on the licence) if it turns out that making the host call is a lot more performant.

2023-11-14 17:19 UTC, richardpringle commented on x/programs/rust/examples/verify/src/types.rs
> +    pub fn as_key(&self) -> &ed25519_dalek::VerifyingKey {
Instead of this, you should just implement [`Deref`](https://doc.rust-lang.org/stable/std/ops/trait.Deref.html)

2023-11-14 17:19 UTC, richardpringle commented on x/programs/rust/examples/verify/src/types.rs
> +}
Same comment about `Deref`

2023-11-14 17:19 UTC, richardpringle commented on x/programs/rust/examples/verify/src/types.rs
> +}
Same comment about `Deref`. You want to get all the `slice` methods [the same way that `Vec` does](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#deref-methods-%5BT%5D)

2023-11-14 17:20 UTC, richardpringle commented on x/programs/rust/examples/verify/src/lib.rs
> +    success_count
I would try this and see if you get a different `wasm` output

2023-11-14 17:20 UTC, richardpringle commented on x/programs/rust/examples/verify/src/lib.rs
> +    success_count
I would try this and see if you get a different `wasm` output

2023-11-14 17:20 UTC, richardpringle commented on x/programs/rust/wasmlanche_sdk/src/host/crypto.rs
> +pub fn verify_ed25519(
This is important

2023-11-14 17:21 UTC, richardpringle commented on x/programs/rust/examples/verify/src/types.rs
> +pub struct BatchPubKeys(pub Vec<EDVerifyingKey>);
I would try this and see if you get a different `wasm` output

2023-11-14 17:22 UTC, richardpringle commented on x/programs/rust/examples/verify/src/types.rs
> +pub struct EDSignatureBytes([u8; EDSignatureBytes::LEN]);
Should these types be in the SDK?

2023-11-14 17:22 UTC, richardpringle commented on x/programs/rust/examples/verify/src/types.rs
> +        pub_keys
I would try this and see if you get a different `wasm` output

2023-12-19 02:33 UTC, samliok commented on x/programs/rust/examples/verify/Cargo.toml
> +rand = "0.8.5"
it doesn't work haha, had this for something earlier on but it's not needed anymore

2024-07-18 18:15 UTC, closed without merging