Remove any reference to the Rust build.sh script
ava-labs/hypersdk pull request #836
Opened 2024-04-16 13:56 UTC by iFrostizz

The `build.sh` script which was used to build Rust programs has been deprecated as per https://github.com/ava-labs/hypersdk/pull/773 and some references were still remaining in the docs.

2024-04-16 14:26 UTC, richardpringle requested changes

2024-04-16 14:26 UTC, richardpringle commented on x/programs/rust/README.md
> +cargo build --target wasm32-wasi --target-dir $CARGO_TARGET_DIR --release
Not sure we should be convincing anyone to use wasi or a specific target-dir
```suggestion
cargo build --target wasm32-unknown-unknown
```

2024-04-16 16:55 UTC, richardpringle approved these changes

2024-04-17 19:08 UTC, darioush approved these changes

2024-04-26 17:05 UTC, merged